version:  "3.8"
services: 
  devcontainer:
    build: .
    image: my_ros_image
    container_name: ROS
    volumes:
      - ~/wenting/su_3d/.devcontainer:/su_3d/.devcontainer
      - ~/wenting/su_3d/code:/su_3d/code
      - ~/wenting/su_3d/data:/su_3d/data
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - /tmp/.X11-unix:/tmp/.X11-unix
    # command: nvidia-smi
    environment:
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable # Very important to enable gui in docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: bash
    stdin_open: true
    tty: true
