# Start from a base image (like Ubuntu)
FROM ubuntu:20.04


# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    git\
    x11-apps

# Add the ROS repository to the sources list
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

# Add the ROS GPG key
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

# Update the package index
RUN apt-get update

# Install a specific ROS package (optional)
# RUN apt-get install -y ros-noetic-desktop-full # Uncomment this will make the building failed

# Source the ROS setup script (optional step to set up environment for containers)
# RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

# Set the default command (optional)
CMD ["/bin/bash"]
